### ISSUE TITLE
Maxmind Parsing Error

### ISSUE THREAD

**Issue by DennisOng** [yellowtree/wp-geoip-detect#11]
Hi Benjamin,

Just installed this on my server and ran into this issue. Would you have any clue as to what this could be related to? 

(It works fine on my local env)

Fatal error: Uncaught exception 'MaxMind\Db\Reader\InvalidDatabaseException' with message 'The MaxMind DB file's data section contains bad data (unknown data type or corrupt data)' in /var/www/tapplecourt/live/wp-content/plugins/geoip-detect/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php:143 Stack trace: #0 /var/www/tapplecourt/live/wp-content/plugins/geoip-detect/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(118): MaxMind\Db\Reader\Decoder->verifySize(8, 13) #1 /var/www/tapplecourt/live/wp-content/plugins/geoip-detect/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php(98): MaxMind\Db\Reader\Decoder->decodeByType('double', 33732811, 13) #2 /var/www/tapplecourt/live/wp-content/plugins/geoip-detect/vendor/maxmind-db/reader/src/MaxMind/Db/Reader.php(64): MaxMind\Db\Reader\Decoder->decode(33732810) #3 /var/www/tapplecourt/live/wp-content/plugins/geoip-detect/vendor/geoip2/geoip2/src/GeoIp2/Database/Reader.php(52): MaxMind\Db\Reader->__construct('/var/www/tapple...') #4 /var/www/tapplecourt/liv in /var/www/tapplecourt/live/wp-content/plugins/geoip-detect/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Decoder.php on line 143

**Comment by benjaminpick** [comment]
Strange error indeed. Which API function did you call? The stacktrace doesn't show (maybe it was clipped off). geoip_detect2_get_info_from_ip() should catch all exceptions, but of course, if he can't read the db, he won't show any info. Maybe the path is incorrect?

**Comment by DennisOng** [comment]
It throws this exception when the .mmdb database is put in the /uploads folder (on both the wp-geoip-detect page in the backend, and the frontend page where geoip_detect2_get_info_from_ip()  is called). I've tried changing the permissions of the file to 777 but it doesn't help either. 

I'm guessing it's a server / php config issue with the VPS, since the exact same code and db is working locally on my machine, but have hit deadends trying to troubleshoot it. Thanks though :)

**Comment by benjaminpick** [comment]
Maybe the mmdb was uploaded in text mode? Because then he might have changed bytes in the file.

**Comment by DennisOng** [comment]
Thanks benjamin,

Is there an easy way to check this? I've tried
1. Uploading via ftp
2. Direct download from the server via wget
3. Downloading by clicking from within the WP backend

All yielding the same results.

**Comment by benjaminpick** [comment]
Well it can only happen via FTP so if you tried the other methods, this
should be ruled out.
I will get back to you when I'll have another idea ...

I've added a commit - can you please test it? It probably doesn't fix
your problem, but
1) there is no script abortion anymore
2) you'll only see the exception only if WP_DEBUG enabled. Also it will
tell you the dir of the file that is actually loaded.

Benjamin

**Comment by DennisOng** [comment]
Sure, giving it a go right now... thanks :)

On a unrelated note, the "install now" button (prompting you to download the database upon plugin activation) is pointing to "tools.php?page=geoip-detect/geoip-detect.php"  (line68 of init.php) ... which will not work if the plugin folder's name is not changed

**Comment by DennisOng** [comment]
Error while creating reader for "/var/www/tc/live/wp-content/uploads/GeoLite2-City.mmdb": The MaxMind DB file's data section contains bad data (unknown data type or corrupt data)

**Comment by oschwald** [comment]
I would first verify the file MD5 on the server. If that looks correct, it is possible that an extension such as mbstring or some other code is overriding a built in string function. The reader does try to detect mbstring and set the appropriate encoding if it is in use, but it is possible that something about your server's configuration is interfering with it.

**Comment by DennisOng** [comment]
Hi oschwald, just checked and the MD5 matched. Thanks though. Is there a way I can check the second issue?

**Comment by oschwald** [comment]
`php -m` should list the extensions installed.

**Comment by DennisOng** [comment]
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
libxml
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
shmop
SimpleXML
sockets

Don't think there's anything out of ordinary here, thoughts?

**Comment by oschwald** [comment]
Yeah, that looks pretty normal to me too. Does it fail only when using this plugin? If you have shell access to the server, it might be worth trying [the MaxMind DB reader](https://github.com/maxmind/MaxMind-DB-Reader-php) separately from the shell to see if you can reproduce the problem there. If so, I'd re-open the bug against that repo.

**Comment by DennisOng** [comment]
Using the MaxmInd DB reader it all works for me (very very strange...)
. I'll spend some time and give a final go on this, will update with results

**Comment by DennisOng** [comment]
Progress : 
1. created a test.php file in the plugins/geoip-detect folder

Tried running a test script with
 $reader = new GeoIp2\Database\Reader('GeoLite2-City.mmdb)
via http://~~~/wp-content/plugins/geoip-detect/test.php 
This works fine.

Tried calling this script in the plugins/geoip-detect/api.php file....
...the wp-admin backend still throwing the same error "he MaxMind DB file's data section contains bad data (unknown data type or corrupt data)"

Not sure why this is failing when called via wordpress. Tried changing folder permissions. Also my whole WP installation is in a symlinked folder, not sure if that's causing any issue....

**Comment by DennisOng** [comment]
Resolved!! Somehow installing the mbstring extension did the trick.

I narrowed down the problem to the findMetadataStart($filename) function in Db\Reader.php. For some reason, 

$markerLength = Util::stringLength($marker);

 was returning the incorrect length when I was running it though WordPress. Adding a +1 to the length solved the issue.

I then tried installing the mb_string extension as I wanted to dig in to find out what was causing the string length issue and hola it was resolved, really odd. 

I really appreciate your input in this issue oschwald and benjamin.

**Comment by oschwald** [comment]
Thanks for reporting back. That is pretty weird. Looking at the code, maybe we could get rid of checking the string length altogether.

**Comment by benjaminpick** [comment]
@oschwald Thank you that you helped me debugging this. Please report back when an upstream fix is available.

**Comment by oschwald** [comment]
[v1.0.3](https://github.com/maxmind/MaxMind-DB-Reader-php/releases/tag/v1.0.3) has been released which does not use `strlen` at all.

**Comment by benjaminpick** [comment]
I've updated this plugin.
