### ISSUE TITLE
Notice: Use of undefined constant GEOIP_DETECT_UPDATER_INCLUDED - assumed 'GEOIP_DETECT_UPDATER_INCLUDED' in /srv/www/eligiblemagazine/htdocs/wp-content/plugins/geoip-detect/init.php on line 50

### ISSUE THREAD

**Issue by pbearne** [yellowtree/wp-geoip-detect#16]
got an PHP warning
( ! ) Notice: Use of undefined constant GEOIP_DETECT_UPDATER_INCLUDED - assumed 'GEOIP_DETECT_UPDATER_INCLUDED' in /srv/www/eligiblemagazine/htdocs/wp-content/plugins/geoip-detect/init.php on line 50
Call Stack
#	Time	Memory	Function	Location
1	0.2030	248200	{main}( )	.../options-general.php:0
2	0.2037	249520	require_once( '/srv/www/eligiblemagazine/htdocs/wp-admin/admin.php' )	.../options-general.php:10
3	2.9624	10757200	require_once( '/srv/www/eligiblemagazine/htdocs/wp-admin/admin-header.php' )	.../admin.php:218
4	3.7850	11211280	do_action( string(17), ??? )	.../admin-header.php:246
5	3.7851	11213144	call_user_func_array:{/srv/www/eligiblemagazine/htdocs/wp-includes/plugin.php:496} ( string(42), array(1) )	.../plugin.php:496
6	3.7851	11213320	geoip_detect_admin_notice_database_missing( string(0) )	.../plugin.php:496

**Comment by pbearne** [comment]
as thease

( ! ) Warning: Illegal string offset 'set_css_country' in /srv/www/eligiblemagazine/htdocs/wp-content/plugins/geoip-detect/views/options.php on line 52
Call Stack
#	Time	Memory	Function	Location
1	0.2030	248200	{main}( )	.../options-general.php:0
2	0.2037	249520	require_once( '/srv/www/eligiblemagazine/htdocs/wp-admin/admin.php' )	.../options-general.php:10
3	3.8077	11211272	do_action( string(39), ??? )	.../admin.php:226
4	3.8078	11212848	call_user_func_array:{/srv/www/eligiblemagazine/htdocs/wp-includes/plugin.php:496} ( string(24), array(1) )	.../plugin.php:496
5	3.8078	11213104	geoip_detect_option_page( string(0) )	.../plugin.php:496
6	3.8206	11219072	include_once( '/srv/www/eligiblemagazine/htdocs/wp-content/plugins/geoip-detect/views/options.php' )	.../admin-ui.php:116
checked="checked"> Add a country-specific CSS class to the <body>-Tag.


( ! ) Warning: Illegal string offset 'has_reverse_proxy' in /srv/www/eligiblemagazine/htdocs/wp-content/plugins/geoip-detect/views/options.php on line 55
Call Stack
#	Time	Memory	Function	Location
1	0.2030	248200	{main}( )	.../options-general.php:0
2	0.2037	249520	require_once( '/srv/www/eligiblemagazine/htdocs/wp-admin/admin.php' )	.../options-general.php:10
3	3.8077	11211272	do_action( string(39), ??? )	.../admin.php:226
4	3.8078	11212848	call_user_func_array:{/srv/www/eligiblemagazine/htdocs/wp-includes/plugin.php:496} ( string(24), array(1) )	.../plugin.php:496
5	3.8078	11213104	geoip_detect_option_page( string(0) )	.../plugin.php:496
6	3.8206	11219072	include_once( '/srv/www/eligiblemagazine/htdocs/wp-content/plugins/geoip-detect/views/options.php' )	.../admin-ui.php:116

**Comment by benjaminpick** [comment]
Thanks for the report, I will fix it when releasing the next version
(the second notice should already be fixed but I'll double-check). For
now, don't worry these notices do not hinder functionality.

On 15.05.2015 20:11, Paul Bearne wrote:
>
> as thease
>
> ( ! ) Warning: Illegal string offset 'set_css_country' in
> /srv/www/eligiblemagazine/htdocs/wp-content/plugins/geoip-detect/views/options.php
> on line 52
> Call Stack
>
>
>   Time Memory Function Location
>
> 1 0.2030 248200 {main}( ) .../options-general.php:0
> 2 0.2037 249520 require_once(
> '/srv/www/eligiblemagazine/htdocs/wp-admin/admin.php' )
> .../options-general.php:10
> 3 3.8077 11211272 do_action( string(39), ??? ) .../admin.php:226
> 4 3.8078 11212848
> call_user_func_array:{/srv/www/eligiblemagazine/htdocs/wp-includes/plugin.php:496}
> ( string(24), array(1) ) .../plugin.php:496
> 5 3.8078 11213104 geoip_detect_option_page( string(0) ) .../plugin.php:496
> 6 3.8206 11219072 include_once(
> '/srv/www/eligiblemagazine/htdocs/wp-content/plugins/geoip-detect/views/options.php'
> ) .../admin-ui.php:116
> checked="checked"> Add a country-specific CSS class to the -Tag.
>
> ( ! ) Warning: Illegal string offset 'has_reverse_proxy' in
> /srv/www/eligiblemagazine/htdocs/wp-content/plugins/geoip-detect/views/options.php
> on line 55
> Call Stack
>
>
>   Time Memory Function Location
>
> 1 0.2030 248200 {main}( ) .../options-general.php:0
> 2 0.2037 249520 require_once(
> '/srv/www/eligiblemagazine/htdocs/wp-admin/admin.php' )
> .../options-general.php:10
> 3 3.8077 11211272 do_action( string(39), ??? ) .../admin.php:226
> 4 3.8078 11212848
> call_user_func_array:{/srv/www/eligiblemagazine/htdocs/wp-includes/plugin.php:496}
> ( string(24), array(1) ) .../plugin.php:496
> 5 3.8078 11213104 geoip_detect_option_page( string(0) ) .../plugin.php:496
> 6 3.8206 11219072 include_once(
> '/srv/www/eligiblemagazine/htdocs/wp-content/plugins/geoip-detect/views/options.php'
> ) .../admin-ui.php:116
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yellowtree/wp-geoip-detect/issues/16#issuecomment-102475158>.
>

-- 

Mit freundlichen Grüßen,

Benjamin Pick
Web-Entwickler

-----------------------------------------------------------------
YELLOW TREE
AGENTUR FÜR DESIGN UND KOMMUNIKATION
-----------------------------------------------------------------
T  +49 (0) 271 703019 - 5
F  +49 (0) 271 703019 - 8
B.PICK@YELLOWTREE.DE <mailto:B.PICK@YELLOWTREE.DE>
WWW.YELLOWTREE.DE
-----------------------------------------------------------------
SANDSTRASSE 173, 57072 SIEGEN
-----------------------------------------------------------------





Rafflenbeul und Utsch GbR
Rechtsform: Gesellschaft des bürgerlichen Rechts
Gesellschafter: 
Heiko Rafflenbeul und Andreas Utsch
Sitz der Gesellschaft: Siegen, Deutschland
Steuer-Nr.: 342 5827 0518
-----------------------------------------------------------------

Diese E-Mail enthaelt vertrauliche oder rechtlich
geschuetzte Informationen.Wenn Sie nicht der
beabsichtigte Empfaenger sind, informieren Sie
bitte sofort den Absender und loeschen Sie diese
E-Mail. Das unbefugte Kopieren dieser E-Mail oder
die unbefugte Weitergabe der enthaltenen
Informationen ist nicht gestattet.
 
The information contained in this message is
confidential or protected by law.If you are not the
intended recipient, please contact the sender and
delete this message. Any unauthorised copying
of this message or unauthorised distribution of the
information contained herein is prohibited.
