### ISSUE TITLE
Not picking up some countries

### ISSUE THREAD

**Issue by klvmedia** [yellowtree/wp-geoip-detect#24]
Hi guys,

I'm having a problem where the plugin is picking up certain countries but not others.

`$userInfo = geoip_detect2_get_info_from_current_ip();`
`if ($userInfo->country->isoCode == 'US'){`
    `echo 'UNITED STATES';`
`} elseif ($userInfo->country->isoCode == 'DE'){`
    `echo 'GERMANY';`
`} elseif ($userInfo->country->isoCode == 'AUS'){`
    `echo 'AUSTRAILIA';`
`} elseif ($userInfo->country->isoCode == 'CAN'){`
    `echo 'CANADA';`
`} elseif ($userInfo->country->isoCode == 'NZL'){`
    `echo 'NEW ZEALAND';`
`} else {`
    `echo 'DEFAULT';`
`}`

This is the code I'm using, and it only picks up the US & Germany but not the others; I've checked the countries iso codes and they seem to be correct. Any ideas or suggestions?

Thank you

**Comment by benjaminpick** [comment]
isoCode is always the two-letter code. See
https://en.wikipedia.org/wiki/ISO_3166-1 Alpha-2-code.

Closes #24.

**Comment by klvmedia** [comment]
Thank you!
