### ISSUE TITLE
GeoIP2 Insight Specific Shortcodes

### ISSUE THREAD

**Issue by freshy84** [yellowtree/wp-geoip-detect#25]
Awesome plugin!

Was wondering if there were any plans to add GeoIP2 Insight Shortcodes? 

The main ones I was after are:
- ISP / Organization			
- Domain

Cheers!

**Comment by benjaminpick** [comment]
They should already work ...
See https://dev.maxmind.com/geoip/geoip2/web-services/ for the full list
of possible properties.

E.g. domain:
[geoip_detect2 property="traits.domain"]

**Comment by freshy84** [comment]
You're a legend!
