### ISSUE TITLE
Cannot redefine GEOIP_DETECT_IP_EMPTY_CACHE_TIME

### ISSUE THREAD

**Issue by Serpentsoft** [yellowtree/wp-geoip-detect#27]
Hi Pal,

I cannot redefine GEOIP_DETECT_IP_EMPTY_CACHE_TIME constant, I still need to wait 2 hours for [0.0.0.0] issue ..

Any suggestion? .. I'm even tried the following 

> 
> function THEME_SLUG_geoip_change_empty_cache_time() {
> 
>     if (! defined('GEOIP_DETECT_IP_EMPTY_CACHE_TIME')) {
> 
>         define('GEOIP_DETECT_IP_EMPTY_CACHE_TIME', 2 * MINUTE_IN_SECONDS);
>     }
> 
> }
> add_action( 'muplugins_loaded', 'THEME_SLUG_geoip_change_empty_cache_time' );

Thanks

**Comment by benjaminpick** [comment]
Did you try it without the function wrapper?

i.e.

if (! defined('GEOIP_DETECT_IP_EMPTY_CACHE_TIME')) {
     define('GEOIP_DETECT_IP_EMPTY_CACHE_TIME', 2 * MINUTE_IN_SECONDS); }

Oh, and are you using the github version of this plugin? Because the
current stable (2.7.0) doesn't has this constant yet.

**Comment by Serpentsoft** [comment]
Ref. [https://wordpress.org/support/topic/external-ip-cache-time-for-developers/] 

Yes i test the defined without function I just try to define the constant inside the function to try define before the plugin load

**Comment by benjaminpick** [comment]
Did you find a solution?  I am declaring my constants in 'plugins_loaded', so you could use this action as well:

```php
add_action( 'plugins_loaded', 'THEME_SLUG_geoip_change_empty_cache_time' , 9);
```

**Comment by benjaminpick** [comment]
Closing this as a stale issue - you can reopen it if you have more information.
