### ISSUE TITLE
Unable to disable country-specific CSS class in the <body> tag

### ISSUE THREAD

**Issue by dklamie** [yellowtree/wp-geoip-detect#28]
After turning it on it can't be disabled.

**Comment by benjaminpick** [comment]
For me, checking the option and unchecking it again works. Can you explain further, please? Which version are you using?

**Comment by dklamie** [comment]
Using Version 2.6.0. Managed to successfully turn it off on Firefox by:
1. first unchecking "Disable caching a page that contains a shortcode or API call to geo-dependent functions."
2. saving the settings and then 
3. unchecking "Add a country-specific CSS class to the <body>-Tag."

If I just uncheck 3. and save, without step no 1. country-specific CSS box remains checked.

**Comment by benjaminpick** [comment]
Thanks for your additional information. But unfortunately I'm still not able to reproduce the bug. Maybe it is a browser bug?

**Comment by benjaminpick** [comment]
Closing this as a stale issue - you can reopen it if you have more information.
