### ISSUE TITLE
Show visitor IP adress in widget text

### ISSUE THREAD

**Issue by Deltaned** [yellowtree/wp-geoip-detect#30]
Hi,

Basic (dummy) user question but on my wordpress website I add a widget text.
What code do I set here to show visitor his IP adres + country + City?)

Thanks

**Comment by benjaminpick** [comment]
Hi, 
Wordpress does not scan for shortcodes in the widgets. Here are 2 easy methods to do this:
http://www.wpbeginner.com/wp-tutorials/how-to-use-shortcodes-in-your-wordpress-sidebar-widgets/

Afterwards, you can use the shortcodes of this plugin:
https://github.com/yellowtree/wp-geoip-detect/wiki/API-Documentation#shortcodes
