### ISSUE TITLE
Relative path gets converted to absolute path

### ISSUE THREAD

**Issue by ch-tactica** [yellowtree/wp-geoip-detect#31]
I have a project hosted on Pantheon using the Manual Data Source option. Works greats, however, when we migrate the database between different hosts we have to constantly go into the backend and resubmit the manual data source since the path seems to be getting converted from a relative to an absolute path.

Is there any way to automate this step to make deployments easier in the future?

**Comment by benjaminpick** [comment]
I see ...

Yes this should be possible, as I am storing both the user input and the
absolute path.

For backwards compat, I would keep using the absolute path, and if the
file is not found, then he will try to use the user input with the new
site root - this should cover your use case, right?

Benjamin

**Comment by benjaminpick** [comment]
Can you test if this commit fixes the issue?
(Download the ZIP and replace the folder. This will show as 2.8.0-beta)

**Comment by ch-tactica** [comment]
@benjaminpick Thanks, it's working great.
