### ISSUE TITLE
not picking up some countries

### ISSUE THREAD

**Issue by Andreas1810** [yellowtree/wp-geoip-detect#33]
I'm following an example given with CSS to show local contacts depending on Country ISO Code.
While it works for Germany and England, it doesn't do it for other countries.
What could be wrong??
Here is my example: (first two work, Italy doesn't)
`<div class="geoip geoip-show-GB">`
`<strong>Your contact in England</strong>`
`Company`
`London`
`England`
`+xx`
`</div>`
`<div class="geoip geoip-show-DE">`
`<strong>Your contact in Germany</strong>`
`Firma`
`Berlin`
`Deutschland`
`+xx`
`</div>`
`<div class="geoip geoip-show-IT">`
`<strong>Your contact in Italy</strong>`
`Compania`
`Milano`
`Italy`
`+xx`
`</div>`

**Comment by benjaminpick** [comment]
You will need to change the CSS code as well (adding geoip-show-IT in the CSS) ...

**Comment by Andreas1810** [comment]
Yes, works. Had to modify the custom.css in the themes folder. Don't understand, however, who put GB and DE in there before ?!
Anyway, nice tool. Thank you.
