### ISSUE TITLE
Update failed. Forbidden

### ISSUE THREAD

**Issue by wgstjf** [yellowtree/wp-geoip-detect#35]
Hi there,

I have just installed the plugin and chosen 'Automatic Download....Maxmind' but the Settings page is showing 'No Maxmind Database Found'.  If I try to 'Update Now' I get the error 'Update Failed. Forbidden'.

Looking in my uploads folder I can see two files of between 1 and 2 Mb named 'GeoIP.dat' and 'GeoIPv6.dat'

I have searched Git and wordpress.org to see if anyone else has had the same issue and got a fix but no luck...any help greatly appreciated. :-)

Cheers,

Will

**Comment by stevenquinn** [comment]
It looks like this is on the Maxmind side of things. Took a little bit of digging but this is the response I'm getting from Cloudflare on their side. This only happens during the download_url() call that's in there, if I just visit the site with my browser, the url works that work.

```
Please enable cookies.
Sorry, you have been blocked

You are unable to access maxmind.com

Why have I been blocked?

This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

What can I do to resolve this?

You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.
```

**Comment by benjaminpick** [comment]
Hi,

thanks for letting me know. Yes I suspected this is a Maxmind issue ...

https://dev.maxmind.com/geoip/geoipupdate/ says they have limited
automatic downloads to their paid users.

However, when I wget the download URL it works.

I would try to change the User-Agent and other properties ... If nothing
works, I will contact the Maxmind support.

Benjamin

**Comment by benjaminpick** [comment]
The update is working again without me changing anything - maybe they are still configuring their cloudflare setup. Let me know if the problem persists on your end.

**Comment by benjaminpick** [comment]
I have changed the User-Agent and did some fine-tuning in the upgrade code. Cloudflare automatically blocked a certain User-Agent because there were too many requests ... Possibly because this plugin scheduled the update at a certain time which was the same for all sites. Adding some random element to spread the load on their server.
