### ISSUE TITLE
Fatal Error with PHP 7.2

### ISSUE THREAD

**Issue by zac-cmn** [yellowtree/wp-geoip-detect#37]
Hi! Thanks for making this awesome plugin. But recently I'm facing an issue. 
When I try to activate the plugin I get this : "Plugin could not be activated because it triggered a fatal error.". It goes away when I change the PHP version to 7.1 or lower. But when I do that I get "Update failed. Forbidden". I thought it is just me until I found atleast one more person having reported this issue in the wordpress support forum. 

Fatal error: Declaration of YellowTree\GeoipDetect\DataSources\Precision\PrecisionReader::city($ip) must be compatible with GeoIp2\WebService\Client::city($ipAddress = ‘me’) in ../wp-content/plugins/geoip-detect/data-sources/precision.php on line 34

**Comment by benjaminpick** [comment]
I will test the plugin with PHP 7.2 ...

(If you have more infos about the update problem, please post it at #35 ...)

Benjamin

**Comment by benjaminpick** [comment]
This was fixed in 302d8f4 - I forgot to release a new version of the plugin, because at the time PHP 7.2 was not stable yet. There will be a release in the coming days.
