### ISSUE TITLE
Fatal Error w/ Advanced Ads Geo Targeting

### ISSUE THREAD

**Issue by stevesearer** [yellowtree/wp-geoip-detect#39]
Good morning and great plugin!

I've recently been integrating the plugin [Advanced Ads](https://wordpress.org/plugins/advanced-ads/) (Pro version - along with their Geo Targeting Add-on) which also uses GeoIP2 geo location. Both plugins work perfectly on their own, but when both are activated I receive the following Fatal Error:

`[02-Feb-2018 01:08:56 UTC] PHP Fatal error: Cannot declare interface GeoIp2\ProviderInterface, because the name is already in use in .../wp-content/plugins/advanced-ads-geo/includes/GeoIp2/ProviderInterface.php on line 5`

I also opened a ticked with the other plugin's author, but thought I would also post here to get your thoughts. 

Thank you!

**Comment by benjaminpick** [comment]
Strange, I thought the composer autoloading takes care of that ... Maybe Advanced Ads Geo did copy this file or include it manually? I cannot check this as it seems to be commercial ...

**Comment by stevesearer** [comment]
@benjaminpick I'll forward this issue thread to the plugin author, thanks!

**Comment by webzunft** [comment]
The author of Advanced Ads here.
We did include the files manually for some reasons and found a fix now, so this can be closed.
