### ISSUE TITLE
Undefined constants depreciated by PHP

### ISSUE THREAD

**Issue by fchaussin** [yellowtree/wp-geoip-detect#40]
Hi guys! 

Thanks for all the good job.

The "Query Monitor" plugin show me those warnings when using the **geoip_detect2_get_info_from_current_ip()** function:

`
Use of undefined constant GEOIP_DETECT_IPV6_SUPPORTED - assumed 'GEOIP_DETECT_IPV6_SUPPORTED' (this will throw an Error in a future version of PHP) | wp-content/plugins/geoip-detect/geoip-detect-lib.php:271
`
`
Use of undefined constant GEOIP_DETECT_IPV6_SUPPORTED - assumed 'GEOIP_DETECT_IPV6_SUPPORTED' (this will throw an Error in a future version of PHP) | wp-content/plugins/geoip-detect/geoip-detect-lib.php:303
`
`
Use of undefined constant GEOIP_DETECT_DOING_UNIT_TESTS - assumed 'GEOIP_DETECT_DOING_UNIT_TESTS' (this will throw an Error in a future version of PHP) | wp-content/plugins/geoip-detect/api.php:74
`
My **PHP** version is : **7.2.3**

**Comment by fchaussin** [comment]
Ok I was using the plugin on this action, works better on `muplugins_loaded` action! 
Thanks

**Comment by hexagongirl** [comment]
I get this same error (or at least the first two), and am using the `plugins_loaded` hook in an mu-plugin.
Is that the correct usage or am I doing things wrong?
Thanks!

**Comment by benjaminpick** [comment]
The plugin uses:
add_action('plugins_loaded', 'geoip_detect_defines');

So the default priority of 10 is used. Can you try using a higher value?

add_action('plugins_loaded', 'your_init_function', 15);


https://developer.wordpress.org/reference/functions/add_action/

**Comment by hexagongirl** [comment]
That fixed it - thanks!
