### ISSUE TITLE
unlink $tmpFile When Updating Database

### ISSUE THREAD

**Issue by donnapep** [yellowtree/wp-geoip-detect#9]
I noticed that the line to unlink the temporary file after updating the database is commented out in `updater.php`:
`//unlink($tmpFile);`

Is there a reason for this? I'd thought that it was the responsibility of the caller to unlink the temp file?

Thx.

**Comment by benjaminpick** [comment]
You're right, this was for debug reasons ...

Benjamin

On 11.01.2015 00:05, Donna Peplinskie wrote:
>
> I noticed that the line to unlink the temporary file after updating
> the database is commented out:
> |//unlink($tmpFile);|
>
> Is there a reason for this? I'd thought that it was the responsibility
> of the caller to unlink the temp file?
>
> Thx.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yellowtree/wp-geoip-detect/issues/9>.
>

-- 

Mit freundlichen Grüßen,

Benjamin Pick
Web-Entwickler

-----------------------------------------------------------------
YELLOW TREE
AGENTUR FÜR DESIGN UND KOMMUNIKATION
-----------------------------------------------------------------
T  +49 (0) 271 703019 - 5
F  +49 (0) 271 703019 - 8
B.PICK@YELLOWTREE.DE <mailto:B.PICK@YELLOWTREE.DE>
WWW.YELLOWTREE.DE
-----------------------------------------------------------------
SANDSTRASSE 173, 57072 SIEGEN
-----------------------------------------------------------------





Rafflenbeul und Utsch GbR
Rechtsform: Gesellschaft des bürgerlichen Rechts
Gesellschafter: 
Heiko Rafflenbeul und Andreas Utsch
Sitz der Gesellschaft: Siegen, Deutschland
Steuer-Nr.: 342 5827 0518
-----------------------------------------------------------------

Diese E-Mail enthaelt vertrauliche oder rechtlich
geschuetzte Informationen.Wenn Sie nicht der
beabsichtigte Empfaenger sind, informieren Sie
bitte sofort den Absender und loeschen Sie diese
E-Mail. Das unbefugte Kopieren dieser E-Mail oder
die unbefugte Weitergabe der enthaltenen
Informationen ist nicht gestattet.
 
The information contained in this message is
confidential or protected by law.If you are not the
intended recipient, please contact the sender and
delete this message. Any unauthorised copying
of this message or unauthorised distribution of the
information contained herein is prohibited.
